CREATE TABLE `games` (
  `id` int NOT NULL AUTO_INCREMENT,
  `slug` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `released` date DEFAULT NULL,
  `tba` tinyint(1) DEFAULT NULL,
  `background_image` varchar(255) DEFAULT NULL,
  `rating` decimal(5,2) DEFAULT NULL,
  `rating_top` int DEFAULT NULL,
  `ratings_count` int DEFAULT NULL,
  `reviews_text_count` varchar(255) DEFAULT NULL,
  `added` int DEFAULT NULL,
  `metacritic` int DEFAULT NULL,
  `playtime` int DEFAULT NULL,
  `suggestions_count` int DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `esrb_rating_id` int DEFAULT NULL,
  `esrb_rating_slug` varchar(255) DEFAULT NULL,
  `esrb_rating_name` varchar(255) DEFAULT NULL,
  `platform_id` int DEFAULT NULL,
  `platform_slug` varchar(255) DEFAULT NULL,
  `platform_name` varchar(255) DEFAULT NULL,
  `platform_released_at` date DEFAULT NULL,
  `platform_requirements_minimum` text,
  `platform_requirements_recommended` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
